{{- if .Values.createRbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Release.Namespace }}-serviceaccount
    namespace: {{ .Release.Namespace }}
{{- end }}
