{{- if and .Values.secret.AWS_ACCESS_KEY_ID .Values.secret.AWS_SECRET_ACCESS_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: |-
    AWS_ACCESS_KEY_ID: {{ .Values.secret.AWS_ACCESS_KEY_ID | b64enc }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.secret.AWS_SECRET_ACCESS_KEY | b64enc }}
{{- end }}
